name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          # Update system and install Docker
          apt update -y
          apt install -y curl git
          
          if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            systemctl start docker
            systemctl enable docker
          fi
          
          # Setup project directory
          mkdir -p /var/www
          cd /var/www
          rm -rf huawei
          
          # Clone repository
          git clone https://github.com/Radiit/huawei-tech-test.git huawei
          cd huawei
          
          # Create environment file
          cat > .env << EOF
          NODE_ENV=production
          PORT=3000
          HOST=0.0.0.0
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DIRECT_URL=${{ secrets.DIRECT_URL }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=7d
          BCRYPT_ROUNDS=12
          RATE_LIMIT_WINDOW_MS=900000
          RATE_LIMIT_MAX_REQUESTS=100
          CORS_ORIGIN=*
          LOG_LEVEL=info
          EOF
          
          # Test database connection before deployment
          echo "Testing database connection..."
          docker run --rm --env-file .env huawei-api node -e "
            const { PrismaClient } = require('@prisma/client');
            const prisma = new PrismaClient();
            prisma.\$connect()
              .then(() => { console.log('✅ Database connection successful'); process.exit(0); })
              .catch(err => { console.error('❌ Database connection failed:', err.message); process.exit(1); });
          " || (echo "Database connection test failed, but continuing with deployment..." && true)
          
          # Deploy application
          docker stop huawei-api || true
          docker rm huawei-api || true
          docker build -t huawei-api .
          docker run -d --name huawei-api -p 3000:3000 --env-file .env --restart unless-stopped huawei-api
          
          # Wait for container to start and check logs
          echo "Waiting for container to start..."
          sleep 10
          
          # Check if container is running
          if ! docker ps | grep -q huawei-api; then
            echo "Container failed to start. Checking logs:"
            docker logs huawei-api
            exit 1
          fi
          
          # Wait for application to be ready
          echo "Waiting for application to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:3000/health >/dev/null 2>&1; then
              echo "Health check passed!"
              break
            fi
            echo "Attempt $i/30: Health check failed, waiting..."
            sleep 2
          done
          
          # Debug: Check container status and network
          echo "Container status:"
          docker ps -a | grep huawei-api
          echo "Container logs (last 20 lines):"
          docker logs --tail=20 huawei-api
          echo "Network connectivity test:"
          docker exec huawei-api sh -c "ping -c 1 db.zvusrfutoxmqkfjllrys.supabase.co || echo 'Ping failed'"
          
          # Final health check with detailed error
          if curl -f http://localhost:3000/health; then
            echo "✅ Final health check passed!"
          else
            echo "❌ Final health check failed. Full container logs:"
            docker logs huawei-api
            echo "Container environment variables:"
            docker exec huawei-api env | grep -E "(DATABASE|SUPABASE)" || echo "No DATABASE/SUPABASE env vars found"
            exit 1
          fi
          
          # Setup cron jobs
          docker exec huawei-api node src/scripts/supabaseCronSetup.js setup || true
          
          echo "Deployment completed successfully!"