name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          # Update system and install Docker
          apt update -y
          apt install -y curl git
          
          if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            systemctl start docker
            systemctl enable docker
          fi
          
          # Setup project directory
          mkdir -p /var/www
          cd /var/www
          rm -rf huawei
          
          # Clone repository
          git clone https://github.com/Radiit/huawei-tech-test.git huawei
          cd huawei
          
          # Create environment file
          cat > .env << EOF
          NODE_ENV=production
          PORT=3000
          HOST=0.0.0.0
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DIRECT_URL=${{ secrets.DIRECT_URL }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=7d
          BCRYPT_ROUNDS=12
          RATE_LIMIT_WINDOW_MS=900000
          RATE_LIMIT_MAX_REQUESTS=100
          CORS_ORIGIN=*
          LOG_LEVEL=info
          EOF
          
          # Deploy application
          docker stop huawei-api || true
          docker rm huawei-api || true
          docker build -t huawei-api .
          docker run -d --name huawei-api -p 3000:3000 --env-file .env --restart unless-stopped huawei-api
          
          # Wait and verify deployment
          sleep 30
          curl -f http://localhost:3000/health || exit 1
          
          # Setup cron jobs
          docker exec huawei-api node src/scripts/supabaseCronSetup.js setup || true
          
          echo "Deployment completed successfully!"